# Generated by Django 4.1.4 on 2023-03-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slugs_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slugs',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
